### PR TITLE
Cleanup / modernize / refactor the JS.

### PR DESCRIPTION
**Pull request by shlomif**
getElementById is almost universally supported - see
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById
. I created a shorter wrapper for the hell of it.

I also placed braces on same line per
https://www.youtube.com/watch?v=hQVTIJBZook .

### CODE REVIEW

**Comment by nkh** [comment]
I'll merge this manually. Please keep the indentation as you find it.

**Comment by shlomif** [comment]
@nkh: OK, but be very careful and test your changes on a local .html file. Removing the unnecessary logic was errorprone for me.

**Comment by nkh** [comment]
commit a0374d5355253419a633151faa7e277172b570fc
Author: Nadim Khemir <nadim.khemir@gmail.com>
Date:   Thu Sep 7 21:20:38 2017 +0200

    CHANGED: DHTML generator. Patch by shlomif.

    ADDED: <meta http-equiv="Content-Type" content="text/html charset=UTF-8">

**Comment by shlomif** [comment]
On Fri, 08 Sep 2017 09:31:13 +0000 (UTC)
Nadim Khemir <notifications@github.com> wrote:

> Closed #32.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Editors and IDEs - http://shlom.in/IDEs

<mst> I find it’s usually safe to assume that whatever shlomif’s doing, there
isn’t a good reason for it.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by nkh** [comment]
Thank you for the patch. What else did you plan? visual cue for folded elements? search that looks better?

**Comment by shlomif** [comment]
On Fri, 08 Sep 2017 10:51:33 +0000 (UTC)
Nadim Khemir <notifications@github.com> wrote:

> Thank you for the patch. 

yw.

> What else did you plan? visual cue for folded
> elements? 

That was my original intention, but it required some cleanups.

> search that looks better?
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Self-Sufficiency/

We agree. But do we agree to agree?

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request closed without merging**
